# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Bash@3
  env:
      BRIDGE_POLARIS_ACCESSTOKEN: $(BRIDGE_POLARIS_ACCESSTOKEN)
      BRIDGE_POLARIS_SERVERURL: $(BRIDGE_POLARIS_SERVERURL)
  inputs:
    polarisService: 'Polaris-POC'
    polarisCommand: 'bridge-cli stage Polaris'
    targetType: 'inline'
    script: |
      curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $(Agent.TempDirectory) bridge.zip && rm -f bridge.zip
          $(Agent.TempDirectory)/synopsys-bridge --stage polaris polaris.assessment.types=SAST,SCA
- task: SynopsysPolaris@1
  inputs:
    polarisService: 'Polaris-POC'
    polarisCommand: 'bridge-cli stage Polaris'
 